/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

/// <reference types="unplugin-vue-router/client" />

import type {
  // type safe route locations
  RouteLocationTypedList,
  RouteLocationResolvedTypedList,
  RouteLocationNormalizedTypedList,
  RouteLocationNormalizedLoadedTypedList,
  RouteLocationAsString,
  RouteLocationAsRelativeTypedList,
  RouteLocationAsPathTypedList,

  // helper types
  // route definitions
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,

  // vue-router extensions
  _RouterTyped,
  RouterLinkTyped,
  RouterLinkPropsTyped,
  NavigationGuard,
  UseLinkFnTyped,

  // data fetching
  _DataLoader,
  _DefineLoaderOptions,
} from 'unplugin-vue-router/types'

declare module 'vue-router/auto/routes' {
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'activity-log': RouteRecordInfo<'activity-log', '/activity-log', Record<never, never>, Record<never, never>>,
    'activity-log-alog-id': RouteRecordInfo<'activity-log-alog-id', '/activity-log/a-log-id', Record<never, never>, Record<never, never>>,
    'activity-log-view-kuota-mitra-id': RouteRecordInfo<'activity-log-view-kuota-mitra-id', '/activity-log/view-kuota-mitra/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'activity-log-view-kuota-mitra-gn-id': RouteRecordInfo<'activity-log-view-kuota-mitra-gn-id', '/activity-log/view-kuota-mitra-gn/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'detail-id': RouteRecordInfo<'detail-id', '/detail/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'detail-form-detail-id': RouteRecordInfo<'detail-form-detail-id', '/detail/form-detail/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'detail-history-panel': RouteRecordInfo<'detail-history-panel', '/detail/history-panel', Record<never, never>, Record<never, never>>,
    'grinus-quota-grinus-jadwal-angsuran': RouteRecordInfo<'grinus-quota-grinus-jadwal-angsuran', '/grinus/quota-grinus-jadwal-angsuran', Record<never, never>, Record<never, never>>,
    'grinus-quota-grinus-kuota': RouteRecordInfo<'grinus-quota-grinus-kuota', '/grinus/quota-grinus-kuota', Record<never, never>, Record<never, never>>,
    'grinus-quota-grinus-kuota-mitra': RouteRecordInfo<'grinus-quota-grinus-kuota-mitra', '/grinus/quota-grinus-kuota-mitra', Record<never, never>, Record<never, never>>,
    'grinus-quota-grinus-submission': RouteRecordInfo<'grinus-quota-grinus-submission', '/grinus/quota-grinus-submission', Record<never, never>, Record<never, never>>,
    'grinus-quota-grinus-submission-status': RouteRecordInfo<'grinus-quota-grinus-submission-status', '/grinus/quota-grinus-submission-status', Record<never, never>, Record<never, never>>,
    'inbox': RouteRecordInfo<'inbox', '/inbox', Record<never, never>, Record<never, never>>,
    'index-old': RouteRecordInfo<'index-old', '/index-old', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'master-data-audit-trail': RouteRecordInfo<'master-data-audit-trail', '/master-data/audit-trail', Record<never, never>, Record<never, never>>,
    'master-data-daftar-mitra': RouteRecordInfo<'master-data-daftar-mitra', '/master-data/daftar-mitra', Record<never, never>, Record<never, never>>,
    'master-data-konfig-mitra': RouteRecordInfo<'master-data-konfig-mitra', '/master-data/konfig-mitra', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'pages-misc-coming-soon': RouteRecordInfo<'pages-misc-coming-soon', '/pages/misc/coming-soon', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'profile-account-settings-tab': RouteRecordInfo<'profile-account-settings-tab', '/profile/account-settings/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'profile-faq': RouteRecordInfo<'profile-faq', '/profile/faq', Record<never, never>, Record<never, never>>,
    'quota-jadwal-angsuran': RouteRecordInfo<'quota-jadwal-angsuran', '/quota/jadwal-angsuran', Record<never, never>, Record<never, never>>,
    'quota-kuota': RouteRecordInfo<'quota-kuota', '/quota/kuota', Record<never, never>, Record<never, never>>,
    'quota-kuota-mitra': RouteRecordInfo<'quota-kuota-mitra', '/quota/kuota-mitra', Record<never, never>, Record<never, never>>,
    'quota-quota-submission': RouteRecordInfo<'quota-quota-submission', '/quota/quota-submission', Record<never, never>, Record<never, never>>,
    'quota-submission-status': RouteRecordInfo<'quota-submission-status', '/quota/submission-status', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'user-management-master-so-list': RouteRecordInfo<'user-management-master-so-list', '/user-management/master-so/list', Record<never, never>, Record<never, never>>,
    'user-management-roles-list': RouteRecordInfo<'user-management-roles-list', '/user-management/roles/list', Record<never, never>, Record<never, never>>,
    'user-management-struktur-organisasi-list': RouteRecordInfo<'user-management-struktur-organisasi-list', '/user-management/struktur-organisasi/list', Record<never, never>, Record<never, never>>,
    'user-management-struktural-list': RouteRecordInfo<'user-management-struktural-list', '/user-management/struktural/list', Record<never, never>, Record<never, never>>,
    'user-management-support-group': RouteRecordInfo<'user-management-support-group', '/user-management/support-group', Record<never, never>, Record<never, never>>,
    'user-management-user-list': RouteRecordInfo<'user-management-user-list', '/user-management/user/list', Record<never, never>, Record<never, never>>,
  }
}

declare module 'vue-router/auto' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export type RouterTyped = _RouterTyped<RouteNamedMap>

  /**
   * Type safe version of `RouteLocationNormalized` (the type of `to` and `from` in navigation guards).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalized<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationNormalizedLoaded` (the return type of `useRoute()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalizedLoaded<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationResolved` (the returned route of `router.resolve()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationResolved<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationResolvedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocation` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocation<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationRaw` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationRaw<Name extends keyof RouteNamedMap = keyof RouteNamedMap> =
    | RouteLocationAsString<RouteNamedMap>
    | RouteLocationAsRelativeTypedList<RouteNamedMap>[Name]
    | RouteLocationAsPathTypedList<RouteNamedMap>[Name]

  /**
   * Generate a type safe params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParams<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['params']
  /**
   * Generate a type safe raw params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParamsRaw<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['paramsRaw']

  export function useRouter(): RouterTyped
  export function useRoute<Name extends keyof RouteNamedMap = keyof RouteNamedMap>(name?: Name): RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  export const useLink: UseLinkFnTyped<RouteNamedMap>

  export function onBeforeRouteLeave(guard: NavigationGuard<RouteNamedMap>): void
  export function onBeforeRouteUpdate(guard: NavigationGuard<RouteNamedMap>): void

  export const RouterLink: RouterLinkTyped<RouteNamedMap>
  export const RouterLinkProps: RouterLinkPropsTyped<RouteNamedMap>

  // Experimental Data Fetching

  export function defineLoader<
    P extends Promise<any>,
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
    isLazy extends boolean = false,
  >(
    name: Name,
    loader: (route: RouteLocationNormalizedLoaded<Name>) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>
  export function defineLoader<
    P extends Promise<any>,
    isLazy extends boolean = false,
  >(
    loader: (route: RouteLocationNormalizedLoaded) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>

  export {
    _definePage as definePage,
    _HasDataLoaderMeta as HasDataLoaderMeta,
    _setupDataFetchingGuard as setupDataFetchingGuard,
    _stopDataFetchingScope as stopDataFetchingScope,
  } from 'unplugin-vue-router/runtime'
}

declare module 'vue-router' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export interface TypesConfig {
    beforeRouteUpdate: NavigationGuard<RouteNamedMap>
    beforeRouteLeave: NavigationGuard<RouteNamedMap>

    $route: RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[keyof RouteNamedMap]
    $router: _RouterTyped<RouteNamedMap>

    RouterLink: RouterLinkTyped<RouteNamedMap>
  }
}
